//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiiliAlytalo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valo
    {
        public int ValoID { get; set; }
        public Nullable<bool> ValoONOFF { get; set; }
        public Nullable<bool> Valo33 { get; set; }
        public Nullable<bool> Valo66 { get; set; }
        public Nullable<bool> Valo100 { get; set; }
        public Nullable<System.DateTime> ValoAikaLeimaONOFF { get; set; }
        public Nullable<System.DateTime> ValoAikaLeima33 { get; set; }
        public Nullable<System.DateTime> ValoAikaLeima66 { get; set; }
        public Nullable<System.DateTime> ValoAikaLeima100 { get; set; }
        public string ValaisinNimi { get; set; }
    }
}
